#!/bin/bash
echo "-------------------------"
echo "   System information"
echo "-------------------------"
echo " Operating system        :" $(cat /etc/os-release |
    grep -i PRETTY_NAME= | sed 's/PRETTY_NAME=//g' | sed 's/"//g')
echo " Kernel name and version :" $(uname -sr) [ $(uname -m) ]
echo "-------------------------"
echo "  Processor information"
echo "-------------------------"
echo -n " Processor type          :" $(lscpu | grep -i Model\ name |
    sed 's/Model name://g' | sed 's/CPU/[/g' | sed 's/GHz/ GHz ]/g' |
    sed '$!N; /^\(.*\)\n\1$/!P; D')
echo
echo " Clocked at              :" $(lscpu | grep -i CPU\ MHz | sed 's/CPU MHz://g') MHz
echo "-------------------------"
echo "  Compilers information"
echo "-------------------------"
echo " GNU Compiler Collection :" $(gcc --version | head -n1)
echo " clang Compiler          :" $(clang --version | head -n1)
echo " Digital Mars D          :" $(dmd -v | head -n1)
echo " LLVM D Compiler         :" $(ldc --version | head -n1)
echo " GNU D Compiler          :" $(gdc --version | head -n1)
echo " Rust Language           :" $(rustc --version)
echo " Nim Language            :" $(nim -h | head -n1)